name: test-check

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Give permissions
        run: chmod +x node_modules/.bin/eslint
      - name: Install Dependancies
        run: npm i
      - name: Lint
        run: npm run lint
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Give permissions
        run: chmod +x node_modules/.bin/jest
      - name: Install Dependancies
        run: npm i
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20
      - name: Test
        run: npm run test